#!/bin/bash
#
# shell script to run mov with external references generator.
# this calls a modified version of ffmbc
# set -x
FFMBC_PATH='/opt/qtwrapper'
if [ "$#" -eq 0 ]; then
	echo "command: ffmov contentfolder startingtimecode outputfilename (without suffix)"
	exit 0
fi
dir="$1"
tcode=$2
output="$dir"/$3.mov
opts='-f s16le -ar 48000 -i '
map='-map_audio_channel '
audioSpec=""
logFile="$dir"/mov.log

#
# if output file exists, rename with number
#
if [ -f "$output" ]; then
    cp "$output" "$output".`date +%s`
fi

i=1
IFS=$'\n'
for path in `ls -1 "$dir"/audio.*`
do

	aspec=""
	curMap=$map$i:0:0:0:$i:0
	aspec=$opts\"$path\"" "$curMap
	audioSpec+=" "$aspec
	let "i++"
done

cmd="$FFMBC_PATH/ffmbc_fast_test -y -v 3 -i \"$dir\"/video.H0 -timecode \"$tcode\" -f s16le -ar 48000 $audioSpec -vcodec copy -acodec copy -strict experimental  -f mov \"$output\" 2> \"$logFile\""

echo $cmd

eval "$cmd"
retcode=$?
#
# if an error occurred, show the tail of the log
#
if [ $retcode -ne 0 ]; then
    echo "ERROR:"
    tail "$logFile"
fi
