#!/bin/bash
#
# shell script to run mov with external references generator.
# this calls a modified version of ffmbc
#
# set -x
FFMBC_PATH='/opt/qtwrapper'
if [ "$#" -eq 0 ]; then
	echo "ffmov contentfolder startingtimecode outputfilename (without suffix)"
	exit 0
fi
dir="$1"
tcode="$2"
output="$1""$3".mov
opts='-f s16le -ar 48000 -i '
map='-map_audio_channel '
audioSpec=""
logFile="$dir"mov.log
#
# if output file exists, rename with number
#
if [ -f "$output" ]; then
    cp "$output" "$output."`date +%s`
fi

i=1
IFS=$'\n'
audiofind="$dir"audio.*
#find "$dir" -type f -name "audio.*" -print0 | while IFS= read -r -d '' path
for path in $(find "$dir" -wholename "$audiofind")
#for path in `ls "$audiofind"`
do
	aspec=""
	curMap=$map$i:0:0:0:$i:0
	aspec=$opts
	aspec+="'$path'"
	aspec+=" "$curMap
	audioSpec+=" "$aspec
	let "i++"
done 
#echo "audiospec"
#echo $audioSpec
videofile="$dir"video.H0
#echo $videofile
#echo $output
cmd="$FFMBC_PATH/ffmbc -y -v 3 -i '$videofile' -timecode '$tcode' -f s16le -ar 48000 $audioSpec -vcodec copy -acodec copy -strict experimental  -f mov '$output' 2> '$logFile'"
eval $cmd
retcode=$?

if [ $retcode -ne 0 ]; then
    echo "ERROR:"
    tail -n 5 "$logFile"
fi
